shell = "zsh"

[plugins]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

[plugins.history-substring-search]
github = 'zsh-users/zsh-history-substring-search'

[plugins.asdf]
github = 'kiurchv/asdf.plugin.zsh'

[plugins.base16]
github = 'chriskempson/base16-shell'

[plugins.fzf-tab]
github = 'Aloxaf/fzf-tab'
